# Generated by Django 2.1.1 on 2018-09-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('transaction_type', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='teamuser',
            unique_together={('team', 'user')},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['id'], name='address_id'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address1'], name='address_address1'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address2'], name='address_address2'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address3'], name='address_address3'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='address_city'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['name'], name='address_name'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postcode'], name='address_postcode'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['id'], name='country_id'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['alpha_2_code'], name='country_alpha_2_code'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['alpha_3_code'], name='country_alpha_3_code'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['english_name'], name='country_english_name'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['phone_prefix'], name='country_phone_prefix'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['primary_level_name'], name='country_primary_level_name'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['id'], name='currency_id'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['name'], name='currency_name'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['id'], name='department_id'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='department_name'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['id'], name='language_id'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['code'], name='language_code'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['english_name'], name='language_english_name'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['native_name'], name='language_native_name'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['id'], name='member_id'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['name'], name='member_name'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['os_id'], name='member_os_id'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['id'], name='profile_id'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['name'], name='profile_name'),
        ),
        migrations.AddIndex(
            model_name='subdivision',
            index=models.Index(fields=['id'], name='subdivision_id'),
        ),
        migrations.AddIndex(
            model_name='subdivision',
            index=models.Index(fields=['alpha_code'], name='subdivision_alpha_code'),
        ),
        migrations.AddIndex(
            model_name='subdivision',
            index=models.Index(fields=['english_name'], name='subdivision_english_name'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['id'], name='team_id'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='team_name'),
        ),
        migrations.AddIndex(
            model_name='territory',
            index=models.Index(fields=['id'], name='territory_id'),
        ),
        migrations.AddIndex(
            model_name='territory',
            index=models.Index(fields=['name'], name='territory_name'),
        ),
        migrations.AddIndex(
            model_name='transactiontype',
            index=models.Index(fields=['id'], name='transaction_type_id'),
        ),
        migrations.AddIndex(
            model_name='transactiontype',
            index=models.Index(fields=['name'], name='transaction_type_name'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='user_id'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['expiry_date'], name='user_expiry_date'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['os_id'], name='user_os_id'),
        ),
    ]
