# Generated by Django 2.0.8 on 2018-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_indexing'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='member',
            name='member_os_id',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_os_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='os_id',
            new_name='api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='os_id',
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['api_key'], name='member_api_key'),
        ),
    ]
