# Generated by Django 2.0.9 on 2018-12-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_remove_openstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='external',
            field=models.BooleanField(default=True),
        ),
    ]
