# Generated by Django 2.0.8 on 2018-12-04 16:06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_external_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontype',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='ss_active',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='xslt',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='xslt_fo',
        ),
    ]
