# Generated by Django 2.2.10 on 2020-03-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_user_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='first_otp',
            field=models.IntegerField(null=True),
        ),
    ]
