# Generated by Django 2.2.13 on 2020-06-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_robot_and_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresslink',
            name='client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='compute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='service_centre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='warrantor',
            field=models.BooleanField(default=False),
        ),
    ]
