# Generated by Django 2.2.11 on 2020-07-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_address_link_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='secret',
            field=models.BooleanField(default=False),
        ),
    ]
