# Generated by Django 2.2.18 on 2021-04-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_app_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errors_found', models.IntegerField()),
                ('finish_time', models.DateTimeField()),
                ('records_inspected', models.IntegerField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
