# Generated by Django 2.2 on 2022-03-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_address_link_references'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresslink',
            old_name='compute',
            new_name='cloud_customer',
        ),
        migrations.AddField(
            model_name='addresslink',
            name='cloud_builder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='cloud_distributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='cloud_seller',
            field=models.BooleanField(default=False),
        ),
    ]
