# Generated by Django 2.2.13 on 2020-06-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_cloud_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresslink',
            name='cloud_export_markup',
            field=models.DecimalField(max_digits=23, decimal_places=4, default='0.0000'),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='cloud_import_markup',
            field=models.DecimalField(max_digits=23, decimal_places=4, default='0.0000'),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='cloud_seller_markup',
            field=models.DecimalField(max_digits=23, decimal_places=4, default='0.0000'),
        ),
    ]
